version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 imagine-api.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=disco_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Zolza0097!
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
